### ISSUE TITLE
slave-priority 翻译错误

### ISSUE THREAD

**Issue by TomeC** [chaopeng/redis-conf#1]
A slave with a low priority number is considered better for promotion, so for instance if there are three slaves with priority 10, 100, 25 Sentinel will pick the one with priority 10, that is the lowest.
我觉得意思是选择优先级数小的作为主服务器。
我的翻译地址：https://github.com/TomeC/cookies/commit/c2e524bcb195f2618d378285e81eae4e22e83a22

**Comment by chaopeng** [comment]
Thank you.
